### ISSUE TITLE
Email is not received with facebook auth?

### ISSUE THREAD

**Issue by n-elloco** [PhilipGarnero/django-rest-framework-social-oauth2#130]
Hello. I make a request to my backend with header
`Authorization: Bearer facebook <token>`
After this request I have a created user in system, but without email. I checked request to facebook and email field is not received. My facebook application is published and I added  parameters 
```
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_FIELDS=id,first_name,last_name,name,email
```

**Comment by aemdy** [comment]
Same issue here as well!

**Comment by gmetaxo** [comment]
In order to get the email of a facebook user, he must have verified his account on facebook. I was experiencing the same issue and created a new facebook user with a verified email for testing and the email was properly sent. So, you need to handle this case -facebook sign up of unverified facebook users- separately.

**Comment by jd-0001** [comment]
@gmetaxo Thanks for your reply. Can you please mention how you handled it? That would be great.

**Comment by gmetaxo** [comment]
@jd-0001 Sorry for the late reply, I got caught up with work and forgot about the question. Well, the solution depends on the actual implementation of the respective app, but I'll share our details in case they are helpful. So, in our case, we needed emails for all users in order to be able to verify their accounts, make reservations and receive important updates/confirmations etc. What we did, is that we added a field on our user profile(a one to one implementation on the user model) to check whether the user had registered through our app, our through social media. In case we received their email through social sign in, we considered the profile complete. Otherwise, we created a permission that would check whether we had emails for social users, and secured the endpoints that needed the email with this permission. If we did not have the email, we would redirect the user to provide us with it, update it on our user profile model and then we had all the information needed for a social user to satisfy our permission. Hope that was useful.

**Comment by jd-0001** [comment]
Hi @gmetaxo that's great currently I am also willing to do this as I am unable to do what [social-auth pipeline](https://python-social-auth.readthedocs.io/en/latest/pipeline.html#partial-pipeline) provides. :disappointed: 

Good things is you can puase the pipeline and ask user for email and if user provides email you can append email with other received data and create user if you have email field as required in your `User` model. However, in our case `email` is required and I am unable to pause the pipeline. See question on [stackoverflow](https://stackoverflow.com/questions/58991950/python-social-auth-partial-pipeline-redirect-gives-httpresponseredirect-object).

If you want the same I will let you know once I will be able to solve this issue of partial pipeline.
