### ISSUE TITLE
Twitter Convert Token Issue

### ISSUE THREAD

**Issue by rachelita** [PhilipGarnero/django-rest-framework-social-oauth2#15]
Hi there,

I followed your instructions and successfully converted my facebook token to a django token via the request:
curl -X POST -d "grant_type=convert_token&client_id=<client_id>&client_secret=<client_secret>&backend=facebook&token=<facebook_token>" http://localhost:8000/auth/convert-token

With Twitter however, I get the following error:
{"error_description": "Backend responded with HTTP403: {\"errors\":[{\"message\":\"Your credentials do not allow access to this resource\",\"code\":220}]}.", "error": "invalid_request"}
I submitted the same curl request but with twitter as the backend and my user_token as the token. I've also tried to add an additional field that uses token_secret that twitter gives me, but I get the same error too. Any thoughts as to why it would work perfectly with facebook but not with Twitter? I can't seem to figure this one out.

Thanks!
Rachel

**Comment by PhilipGarnero** [comment]
Actually, I never tested twitter with convert token and I just figured out it does not work exactly as I expected.
In fact the social auth backend expects a query string instead of a simple token.
You can figure this out by looking at the do_auth function of the python-social-auth backend (in this case the twitter backend code).

I managed to get this to work by putting `oauth_token=<token>&oauth_token_secret=<secret_token>` in the token field.

So in a curl command this should look like this : `curl -X POST -d "grant_type=convert_token&client_id=<client_id>&backend=twitter&token=oauth_token=<token>%26oauth_token_secret=<secret_token>" http://localhost:8000/auth/api/convert-token`
%26 is the ampersand character (&) encoded.

Well, this is not really user friendly but I don't want to put special cases everywhere in the code and I prefer to let the backend/user couple handle this. I chose the same behavior (i.e. not doing anything) for error responses as all backends won't respond the same way.

Feel free to close the issue when you are okay with this

**Comment by rachelita** [comment]
thanks!

**Comment by murabo** [comment]
Does this method fail authentication now?

**Comment by professorhaseeb** [comment]
[This solution](https://github.com/RealmTeam/django-rest-framework-social-oauth2/issues/15#issuecomment-138943763) doesn't really work for me...

![image](https://user-images.githubusercontent.com/1492888/76534197-fa948500-649a-11ea-863f-030b77438c87.png)
