### ISSUE TITLE
Mock a backend response

### ISSUE THREAD

**Issue by BraisGabin** [PhilipGarnero/django-rest-framework-social-oauth2#40]
I want to test my backend. How can I mock the Facebook (or other backend) responses? I want to define a list of "valid tokens" and which are the Facebook responses for them.

**Comment by PhilipGarnero** [comment]
Well, I've looked into python-social-auth but there doesn't seem to be a normalized way to do this.

I think the best way to do this would be to create a facebook "test" backend.
During your tests, instead of using the normal Facebook backend you would create the fake one and use it instead.
That's a lot of work especially if you are using multiple backends.
A good idea that comes to mind is to implement the test backends directly into python-social-auth so other users could help with every backend.

Feel free to reopen if you have more questions.

**Comment by BraisGabin** [comment]
I found a solution: https://github.com/omab/python-social-auth/issues/414#issuecomment-227471374
