### ISSUE TITLE
SSO Authentication with JWT

### ISSUE THREAD

**Issue by alexislg2** [PhilipGarnero/django-rest-framework-social-oauth2#41]
Hey,
I'm developing a mobile app and I want to use social authentication for Single Sign On. I want my user to log in using FB/Google ONLY ONCE in the app lifetime.

So what I want to do is:
1. User logs in using the app to FB/Google.
2. FB/Google returns an access_token
3. The app sends this access_token to Django backend using POST request
4. Django Backends find the user associated to this FB account or creates a new one using first name, last name and email from FB account
5. Django returns a JWT token for further authentication with infinite lifetime
6. The JWT is saved on the mobile application
7. Next the app uses this JWT to authenticate the user and then no more FB log in is necessary

Can I do that with your package? How?

**Comment by alexislg2** [comment]
OK quite easy with your plugin:
Just creat a route /api/get-user that return a JWT from the given user

then curl -H "Authorization: Bearer <backend_name> <access_token>" http://localhost:8000/api/get-user

And that's it! Thanks for this amazing plugin

**Comment by kinesii** [comment]
@alexislg2 Can you please elaborate about how you achieved this?

**Comment by alexislg2** [comment]
@kinesii What exactly do you need?

**Comment by assembledadam** [comment]
@alexislg2 Does the request to /api/get-user contain any authentication in itself, or just the user data?

If just the user data, this is very insecure. An attacker could simply call that endpoint with someone's user and get infinite access to their account.

A better way would be to extend your django-rest-framework-social-oauth2 endpoint to return a JWT instead of the standard access token on the initial authentication request.

**Comment by alexislg2** [comment]
@assembledadam the /api/get-user requests to provide the `access_token` provided by the OAuth backend. So an attacker would need this `access_token` so he would need to have the Google/Facebook password of the user he wants to hack
